defaults:
  - _self_
  - data: var # choose datamodule with `test_dataloader()` for evaluation
  - model: resnet
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "test"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2025-03-02_08-14-14/checkpoints/epoch_051.ckpt
